### ISSUE TITLE
How to predict joint parameters?

### ISSUE THREAD

**Issue by KunalMGupta** [Salingo/RPM-Net#2]
Hi! Congratulations on the cool work with RPMNet. The paper also mentions the Mobility-Net for predicting joint parameters but I am unable to find it in the code base. Can you please point me to where I can get that?

Thanks!

**Comment by Salingo** [comment]
Hi,
Thanks for your interest! This repository is only for RPM-Net, thus we did not release the code for Mobility-Net. The parameters of Mobility-Net are provided in our supplementary material, which you can download from our [project page](https://vcc.tech/research/2019/RPMNet).

**Comment by KunalMGupta** [comment]
Okay thanks.
