### ISSUE TITLE
Out of memory at the start of stage 3 of training

### ISSUE THREAD

**Issue by ShnitzelKiller** [Salingo/RPM-Net#3]
Is a Titan Xp insufficient for training this model? How much VRAM does RPM-Net require? Are there recommended ways to reduce the memory usage with the least impact on quality?

**Comment by Salingo** [comment]
Hi, we train the RPM-Net using 4 GPUs, and each of them has 32GB of memory.
A direct way to reduce the GPU memory cost is setting a smaller batch size, also, you can try to reduce the output frames number (num_frame).
Thanks!
